default_platform(:android)

platform :android do
  desc "Distribute production build to Firebase"
  lane :release_to_firebase do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"

    firebase_app_distribution(
      app: "1:889803121743:android:af6d1fc6635c72af7cb63a",
      firebase_cli_token: "1//03UZayABoItjjCgYIARAAGAMSNgF-L9Irxu4JTko39LWiKYKDDLctvPiNIeX1TscqKFE_HWT5p9AMnt-PFeHzDwIuCIadmrZ1VQ",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "aelbaz0189@gmail.com",
      release_notes: "test this version of the app"
    )
  end
end
