name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main   # أو غيّرها لو عندك الفرع main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    # Cache Flutter pub packages
    - name: Cache Flutter dependencies
      uses: actions/cache@v2
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

    - name: Flutter Pub Get
      run: flutter pub get

    - name: Setup Ruby & Fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2.3"
        bundler-cache: true
        working-directory: android

    - name: Build and Distribute App to Firebase
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        bundle exec fastlane android release_to_firebase
      working-directory: android

    # Upload APK as Artifact (optional but useful)
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/*.apk
